POST http://127.0.0.1:5000/openai 
Content-Type: application/json

{
    "language": "python",
    "content": "f(x) = x^3 + 2x + 1 with the constraint x≥2",
    "type": "code"
}

###
GET http://127.0.0.1:5000/image-to-expression
# Content-Type: application/json
