name: Auto Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into Azure VM and pull changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_SSH_PASSWORD }}
        port: ${{ secrets.AZURE_VM_SSH_PORT }}
        script: |
          cd ntu-fast-fingers
          git pull
